Asset repository
y-tree-limited/YehorUsTraineePrivateRepo pull request #4
Opened 2021-07-26 14:36 UTC by FairyTalePol

Added repositories:
Asset, Private asset, Public asset, Asset-User relations, Asset-Group relations
Modified database and added tests

2021-07-27 10:54 UTC, sn3jkeee requested changes

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/AssetTest.kt
> +
empty line

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/AssetTest.kt
> +@SpringBootTest
Why its @SpringBootTest?

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/AssetTest.kt
> +        Assertions.assertEquals(expectedAsset, asset.orElse(AssetEntity(15.0, "General Motors")))
Please dont use static class import. Use static method import instead.
```
//Then
assertEquals(expectedAsset, asset.orElse(AssetEntity(15.0, "General Motors")))
```

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/AssetTest.kt
> +        em.persist(expectedAsset)
Better to em.flush() to make sure you actually insert and them update

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/GroupAssetRelationRepositoryTest.kt
> +@SpringBootTest(
Such test should be @DataJpaTest

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/PrivateAssetTest.kt
> +
empty lines

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/PublicAssetTest.kt
> +        try{
space after try please

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/PublicAssetTest.kt
> +        //When
Please add empty line before each block Given/When/Then

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/UserAssetRelationRepositoryTest.kt
> +
empty line

2021-07-27 10:54 UTC, sn3jkeee commented on src/test/kotlin/com/example/springrestuser/repositories/UserGroupTests.kt
> +        val actual = repo.findByUserIdAndGroupId(user2.id?:0, group2.id?:0)
please add spaces

2021-07-27 11:21 UTC, FairyTalePol commented on src/test/kotlin/com/example/springrestuser/repositories/AssetTest.kt
> +@SpringBootTest
Because Flyway requires Sprig Boot cotext to perform migrations

2021-07-28 13:09 UTC, sn3jkeee approved these changes

2021-07-28 13:31 UTC, merged