aa
y-tree-limited/YehorUsTraineePrivateRepo pull request #6
Opened 2021-08-02 08:28 UTC by FairyTalePol

a

2021-08-02 10:34 UTC, ginsenghillock requested changes

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/do/UserAssetDO.kt
> +}
Are you sure that it has to be var instead of val?

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/dto/StatisticsDTO.kt
> +}
```suggestion
data class StatisticsDTO(
    @JsonProperty("body")
    val firstName: Map<String, String> = mutableMapOf()
)
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/dto/StatisticsDTO.kt
> +}
why do you need a default value actually?

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/dto/StatisticsDTO.kt
> +}
And variable name is kinda strange

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/enums/AssetType.kt
>  }
```suggestion
    PRIVATE,
    PUBLIC
}
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/exceptions/AssetAlreagyAssignedException.kt
> +class AssetAlreadyAssignedException(assetId: Int, toId: Int) : RuntimeException("Asset $assetId already assigned to user/group $toId"){}
```suggestion
class AssetAlreadyAssignedException(assetId: Int, toId: Int) : RuntimeException("Asset $assetId already assigned to user/group $toId")
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/exceptions/AssetGroupPairDoesNotExist.kt
> +class AssetGroupPairDoesNotExist(assetId: Int, groupId: Int) : RuntimeException("Group $groupId does not own asset $assetId"){}
```suggestion
class AssetGroupPairDoesNotExist(assetId: Int, groupId: Int) : RuntimeException("Group $groupId does not own asset $assetId")
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/exceptions/AssetNotFoundException.kt
> +}
```suggestion
class AssetNotFoundException(id: Int) : RuntimeException("Could not find asset $id")
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/repositories/GroupAssetRelationRepository.kt
> +    fun findByAssetIdAndGroupId(assetId: Int, groupId: Int): List<GroupAssetRelationEntity?>?
```suggestion
    fun findByAssetIdAndGroupId(assetId: Int, groupId: Int): List<GroupAssetRelationEntity>
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/repositories/GroupAssetRelationRepository.kt
> +    fun findByAssetIdAndGroupId(assetId: Int, groupId: Int): List<GroupAssetRelationEntity?>?
I don't think that it is a good idea to return null or list of nulls

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/repositories/UserAssetRelationRepository.kt
> +    fun findByAssetIdAndUserId(assetId: Int, userId: Int): List<UserAssetRelationEntity?>?
```suggestion
    fun findByAssetIdAndUserId(assetId: Int, userId: Int): List<UserAssetRelationEntity>
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/repositories/UserAssetRelationRepository.kt
> +    fun findByAssetIdAndUserId(assetId: Int, userId: Int): List<UserAssetRelationEntity?>?
I don't think that it is a good idea to return null or list of nulls

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/AssetService.kt
> +    }
```suggestion
    fun getAsset(assetId: Int): AssetDO = assetStorage.getAsset(assetId)
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/AssetService.kt
> +    }
```suggestion
    fun deleteAsset(assetId: Int) {
       assetStorage.deleteAsset(assetId)
    }
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/AssetService.kt
> +    }
```suggestion
    fun getAllAssets (assetId: Int) {
       assetStorage.deleteAsset(assetId)
    }
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/GroupAssetService.kt
> +    }
```suggestion
    fun getAssetIdByGroupId(userId: Int): List<Int> = storage.getAssetsIdByGroup(userId)
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/GroupAssetService.kt
> +    }
```suggestion
    fun getGroupsIdByAssetId(groupId: Int): List<Int>  = storage.getGroupsIdByAsset(groupId)
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/GroupAssetService.kt
> +        if (quantity<1) throw NegativeQuantityException(assetId, quantity)
```suggestion
        if (quantity < 1) throw NegativeQuantityException(assetId, quantity)
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/GroupAssetService.kt
> +        }
pls, decide if you use `if` statement with `{}` or not

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/PrivateAssetService.kt
> +    }
```suggestion
    fun get(assetId: Int): PrivateAssetDO = runCatching { privateAssetStorage.get(assetId) }.getOrElse { throw AssetNotFoundException(assetId) }
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/PrivateAssetService.kt
> +        return runCatching { privateAssetStorage.delete(assetId) }.getOrElse { throw AssetNotFoundException(assetId) }
```suggestion
       runCatching { privateAssetStorage.delete(assetId) }.getOrElse { throw AssetNotFoundException(assetId) }
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/PrivateAssetService.kt
> +    }
```suggestion
    fun getAll(assetId: Int): List<PrivateAssetDO> = privateAssetStorage.getAll()
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/PrivateAssetService.kt
> +    }
```suggestion
    fun add(privateAssetDO: PrivateAssetDO): PrivateAssetDO = privateAssetStorage.add(privateAssetDO)
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/services/StatisticsService.kt
> +
```suggestion
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/storage/AssetStorage.kt
> +//        val res = mutableListOf<AssetDO>()
it is a bad practice to leave commented code

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/storage/AssetStorage.kt
> +        return assetDO
```suggestion
    private fun toAssetDO(assetEntity: AssetEntity): AssetDO =
        AssetDO(assetEntity.price, assetEntity.description, AssetType.valueOf(assetEntity.type)).apply {
          id = assetEntity.id
        }
```

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/storage/GroupAssetRelationStorage.kt
> +            groupAssetRelation?.quantity = groupAssetRelation?.quantity?.plus(quantity)!!
Use !! with caution. It could lead to a null pointer exception. It's better to provide some default value

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/storage/GroupAssetRelationStorage.kt
> +//    fun getAssetsByGroup(groupId: Int): List<AssetDO> {
commented code

2021-08-02 10:34 UTC, ginsenghillock commented on src/main/kotlin/com/example/springrestuser/storage/UserAssetRelationStorage.kt
> +            if (asset != null && asset.asset.type==assertTypeFilter.toString()) {
Just do not return a list with nulls and then you don't have to check if the asset is null.

2021-08-02 10:45 UTC, FairyTalePol commented on src/main/kotlin/com/example/springrestuser/do/AssetDO.kt
> +}
Well, in Domain Objects it should be val i think. But not the ID. If I put id to the constructor, it will be included in .equals(), and I dont want ID to be compared. So for all fields except ID i will change var to val

2021-08-02 14:58 UTC, sn3jkeee requested changes

2021-08-02 14:58 UTC, sn3jkeee commented on src/main/kotlin/com/example/springrestuser/services/StatisticsService.kt
> +        return StatisticsDO(map)
For me looks like bad approach. You service controlling JSON that will be returned to clients

2021-08-03 10:36 UTC, sn3jkeee approved these changes

2021-08-03 10:37 UTC, merged